export const API_URL = "http://" + window.location.hostname + ":8000";

export const WS_URL = "ws://" + window.location.hostname + ":8000";

export const API_ROUTES = {
    SIGN_UP: 					`${API_URL}/auth/signup`,
	VERIFY_EMAIL: 				`${API_URL}/auth/verifyemail`,
	SIGN_IN: 					`${API_URL}/auth/signin`,
	FORGOT_PASSWORD: 			`${API_URL}/auth/forgotpassword`,
	FORGOT_USERNAME: 			`${API_URL}/auth/forgotusername`,
	CHANGE_PASSWORD: 			`${API_URL}/auth/changepassword`,
	SIGN_OUT: 					`${API_URL}/auth/signout`,
	REFRESH: 					`${API_URL}/auth/refresh`,
	IS_CONNECTED: 				`${API_URL}/auth/isconnected`,
    IS_COMPLETE_PROFILE:        `${API_URL}/profile/iscompleteprofile`,
    COMPLETE_PROFILE:           `${API_URL}/profile/completeprofile`,
	//UPDATE_FIRSTNAME:			`${API_URL}/profile/updatefirstname`,
	//UPDATE_LASTNAME: 			`${API_URL}/profile/updatelastname`,
	UPDATE_PREFERENCES:			`${API_URL}/profile/updatepreferences`,
	UPDATE_BIO:           		`${API_URL}/profile/updatebio`,
	UPDATE_PICTURES:      		`${API_URL}/profile/updatepictures`,
	UPDATE_INTERESTS:      		`${API_URL}/profile/updateinterests`,
	UPDATE_PASSWORD:      		`${API_URL}/profile/updatepassword`,
	UPDATE_EMAIL:         		`${API_URL}/profile/updateemail`,
	VERIFY_NEW_EMAIL: 			`${API_URL}/profile/verifyemail`,
	UPDATE_USERNAME:      		`${API_URL}/profile/updateusername`,
	UPDATE_GPS:					`${API_URL}/profile/updategps`,
	UPDATE_LOCATION:			`${API_URL}/profile/updatelocation`,
	GET_GPS:					`${API_URL}/profile/getgps`,
    GET_PROFILE_USER:           `${API_URL}/profile/getprofileuser`,
	NOTIF_VERIFIED:				`${API_URL}/profile/notifverified`,
	LIKE:                 		`${API_URL}/interaction/like`,
	DISLIKE:              		`${API_URL}/interaction/dislike`,
	BLOCK:                		`${API_URL}/interaction/block`,
	VIEW:                 		`${API_URL}/interaction/view`,
	REPORT:               		`${API_URL}/interaction/report`,
	GET_MY_CONVERSATIONS: 		`${API_URL}/interaction/getmyconversations`,
	GET_MESSAGES:         		`${API_URL}/interaction/getmessages`,
	GET_MATCHS:         		`${API_URL}/interaction/getmatchs`,
	GET_RESEARCH:				`${API_URL}/interaction/getresearch`,
	GET_ALL_INTERESTS:          `${API_URL}/data/listinterests`,
	ADMIN_AUTH_EMAIL:			`${API_URL}/admin/auth`,
	ADMIN_AUTH_CODE:			`${API_URL}/admin/verification`,
};

export const APP_ROUTES = {
    WELCOME: "/",
    SIGN_UP: "/signup",
    SIGN_IN: "/signin",
    TOKEN_MAIL: "/token_mail",
	TOKEN_NEWMAIL: "/token_newmail",
    TOKEN_PASSWORD: "/token_password",
    PARAMETERS: "/parameters",
    DASHBOARD: "/dashboard",
    MATCH: "/match",
    CONVERSATION: "/conversation",
    NOTIFICATION: "/notification",
    COMPLETE_PROFILE: "/complete-profile",
	ADMIN: "/admin"
};
